### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by cfljam** [vladsaveliev/TargQC#1]
Im able to install but targqc fails with same error shown in TRavis

```
    from ngs_utils.bedtools import BedTool
ImportError: No module named bedtools
```

which looks to be an issue with the https://github.com/vladsaveliev/NGS_Utils

**Comment by vladsaveliev** [comment]
Thanks cfljam a lot the bug report. I just pushed changes to address this error, look like Travis just passed the tests.

So I've been keeping updating NGS_Utils lately, but I forgot to address corresponding changes in TargQC which is referencing the latest of that repo, and they became out of sync. Most of the TargQC features is now integrated in bcbio-nextgen and I kind of moved away from using it and supporting. However now it's all good. If you want to run it, you gonna need to reinstall it to make sure the latest NGS_Utils is pulled.

**Comment by cfljam** [comment]
Thanks for the fast response! We are working in non-human plant genomes and at present bcbio-nextgen is a bit daunting for our needs.
This update installs and runs ok but fails since I naively passed an indexed reference. Its not obvious to me how to register a genome for ngsutils in _my_conda_env//lib/python2.7/site-packages/ngs_utils/reference_data/ for a non-Ensembl source. Is there an ngsutils script for this?

```
ngs_utils.logger.CriticalError: Genome /workspace/cfljam/HighHealth/PoolSeq/PS1_reference/PS1_1.68.5.fasta is not supported. Supported genomes: hg19, hg19-noalt, hg38, hg38-noalt, hg19-chr21, GRCh37, mm10
```

**Comment by vladsaveliev** [comment]
Unfortunately it's not possible now, the tool was never tested with non-human/mouse references. Sorry about that. However I think it shouldn't be hard to start supporting arbitrary genomes, I'm actually gonna take a look on that on the weekend and will let you know.

**Comment by cfljam** [comment]
Standing by for testing!

**Comment by vladsaveliev** [comment]
Hi John, so I pushed a few changes, and now you can use the `-g` option to specify a path to any custom reference, like this:
`targqc *.bam --bed target.bed  -o results -g /workspace/cfljam/HighHealth/PoolSeq/PS1_reference/PS1_1.68.5.fasta`

Make sure that the fasta file has a `.fai` index located at the same directory (if not, run `samtools faidx PS1_1.68.5.fasta` to generate one). Basically the reference itself is not required since targqc only needs the `.fai` file. However, if you run from fastq rather than BAM files, a reference fasta file will be required, as well as also bwa index files to be located at the same directory.

Let me know how it goes. I didn't test much except for a small local project, hope it works okay in you case.

**Comment by cfljam** [comment]
This is working now with my bams + fasta-will update and close when it completes. Many thanks !

**Comment by cfljam** [comment]
Compiling the summary report failed initially due to targqc not finding the sambamba dependency but completed fine when I installed into my conda env from bioconda. A bioconda recipe for TargQC would be very helpful.

**Comment by vladsaveliev** [comment]
Great to hear, I'm doing to make the recipe right away. Conda is great, but I learned about that so recently.

**Comment by cfljam** [comment]
We would like to install in our HPC system for QC and my colleague @timothymillar  can help testing Conda so let us know if you do this

**Comment by vladsaveliev** [comment]
Hi, John, I finally managed to create the bioconda recipe for targqc and get approved. Would be nice if you plan to give it a try. Note that it's only python 2.7 and only linux now - I'm working on making a python 3 package and also figure how to make it available for osx.
